name: Build JSON from .alist

permissions:
  contents: write

on:
  push:
    paths:
      - 'air/data/**.alist'
      - 'air/data/airports.csv'
      - 'air/scripts/build_data.py'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run build script
        run: python air/scripts/build_data.py

      - name: Check for unknown airport codes
        run: python air/scripts/check_unknown_codes.py

      - name: Commit unknown_codes.txt
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add air/data/unknown_codes.txt
          git commit -m "Update list of unknown airport codes" || echo "Nothing to commit"
          git push origin master

      - name: Commit and push updated JSON
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add air/data/*.json
          git commit -m "Auto-update JSON from .alist" || echo "Nothing to commit"
          git push origin master
