name: Deploy Airport Maps

on:
  workflow_run:
    workflows: ["Build JSON from .alist"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and Deploy to GitHub Pages
        uses: actions/configure-pages@v3
      # Add additional steps here as needed based on your actual deployment logic
